# Generated by Django 3.2.17 on 2023-03-01 08:27

from django.db import migrations, models
import django.db.models.deletion
import personal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=1)),
                ('birth_date', models.DateField(verbose_name='birth date')),
                ('join_date', models.DateField(verbose_name='join date')),
                ('position', models.CharField(max_length=30)),
                ('avatar', models.ImageField(null=True, upload_to=personal.models.upload_location)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
                ('progress', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usernames',
            fields=[
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='personal.employees')),
                ('username', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='employees',
            name='state_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.states'),
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateField(auto_now_add=True, verbose_name='scan date')),
                ('percent_N', models.FloatField()),
                ('percent_S', models.FloatField()),
                ('percent_L', models.FloatField()),
                ('count_N', models.IntegerField()),
                ('count_S', models.IntegerField()),
                ('count_L', models.IntegerField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.employees')),
            ],
            options={
                'unique_together': {('employee_id', 'scan_date')},
            },
        ),
    ]
