# Generated by Django 3.2.17 on 2023-03-01 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employee',
        ),
        migrations.RenameModel(
            old_name='Results',
            new_name='Result',
        ),
        migrations.RenameModel(
            old_name='States',
            new_name='State',
        ),
        migrations.RenameModel(
            old_name='Usernames',
            new_name='Username',
        ),
    ]
