# Generated by Django 4.1.7 on 2023-03-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_result_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='progress',
            field=models.CharField(blank=True, choices=[('I', 'Improved'), ('S', 'Stable'), ('W', 'Worsened')], max_length=10),
        ),
    ]
